-- MySQL Script generated by MySQL Workbench
-- Mon Jul 18 16:57:19 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jumbofood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jumbofood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jumbofood` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `jumbofood` ;

-- -----------------------------------------------------
-- Table `jumbofood`.`_prisma_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`_prisma_migrations` (
  `id` VARCHAR(36) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  `finished_at` DATETIME(3) NULL DEFAULT NULL,
  `migration_name` VARCHAR(255) NOT NULL,
  `logs` TEXT NULL DEFAULT NULL,
  `rolled_back_at` DATETIME(3) NULL DEFAULT NULL,
  `started_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `applied_steps_count` INT UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`admin` (
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(1000) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`categorieproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`categorieproduit` (
  `nom` VARCHAR(1000) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`produit` (
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prix` INT NULL DEFAULT NULL,
  `photoURL` VARCHAR(1000) NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `categorieproduitId` INT NULL DEFAULT NULL,
  `statut` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Produit_CategorieProduit1_idx` (`categorieproduitId` ASC) VISIBLE,
  CONSTRAINT `fk_Produit_CategorieProduit1`
    FOREIGN KEY (`categorieproduitId`)
    REFERENCES `jumbofood`.`categorieproduit` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`catalogue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`catalogue` (
  `quantite` INT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `dateApprovisionnement` DATE NULL DEFAULT NULL,
  `updatedAt` DATETIME(3) NOT NULL,
  `produitId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produit_idx` (`produitId` ASC) VISIBLE,
  CONSTRAINT `fk_produit`
    FOREIGN KEY (`produitId`)
    REFERENCES `jumbofood`.`produit` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`client` (
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(45) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`packproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`packproduit` (
  `prix` INT NULL DEFAULT NULL,
  `description` VARCHAR(1000) NULL DEFAULT NULL,
  `photoURL` VARCHAR(1000) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`pointramassage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`pointramassage` (
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `longitude` DOUBLE NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`pannier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`pannier` (
  `prix` DOUBLE NOT NULL,
  `date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `moyenPaiement` VARCHAR(45) NOT NULL,
  `statut` VARCHAR(45) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `clientId` INT NULL DEFAULT NULL,
  `pointramassageId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idClient_idx` (`clientId` ASC) VISIBLE,
  INDEX `idPointRamassage_idx` (`pointramassageId` ASC) VISIBLE,
  CONSTRAINT `clientId`
    FOREIGN KEY (`clientId`)
    REFERENCES `jumbofood`.`client` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `pointramassageId`
    FOREIGN KEY (`pointramassageId`)
    REFERENCES `jumbofood`.`pointramassage` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`ligneproduit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`ligneproduit` (
  `prix` INT NULL DEFAULT NULL,
  `quantite` INT NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `pannierId` INT NULL DEFAULT NULL,
  `produitId` INT NULL DEFAULT NULL,
  `packproduitId` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idPannier_idx` (`pannierId` ASC) VISIBLE,
  INDEX `idProduit_idx` (`produitId` ASC) VISIBLE,
  INDEX `idPack_idx` (`packproduitId` ASC) VISIBLE,
  CONSTRAINT `packproduitId`
    FOREIGN KEY (`packproduitId`)
    REFERENCES `jumbofood`.`packproduit` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `pannierId`
    FOREIGN KEY (`pannierId`)
    REFERENCES `jumbofood`.`pannier` (`id`)
    ON DELETE SET NULL,
  CONSTRAINT `produitId`
    FOREIGN KEY (`produitId`)
    REFERENCES `jumbofood`.`produit` (`id`)
    ON DELETE SET NULL)
ENGINE = InnoDB
AUTO_INCREMENT = 53
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`producteur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`producteur` (
  `numero` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(45) NULL DEFAULT NULL,
  `latitude` DOUBLE NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `preinscriptionValide` VARCHAR(45) NULL DEFAULT 'en attente',
  `longitude` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`producteur_has_produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`producteur_has_produit` (
  `producteurId` INT NOT NULL AUTO_INCREMENT,
  `produitId` INT NOT NULL,
  `conditionnement` VARCHAR(45) NULL DEFAULT NULL,
  `frequenceProduction` VARCHAR(45) NULL DEFAULT NULL,
  `photoURL` VARCHAR(1000) NULL DEFAULT NULL,
  `saisonnier` VARCHAR(45) NULL DEFAULT NULL,
  `statut` VARCHAR(45) NULL DEFAULT 'en attente',
  `volumeProduction` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`producteurId`, `produitId`),
  INDEX `fk_Producteur_has_Produit_Producteur1_idx` (`producteurId` ASC) VISIBLE,
  INDEX `fk_Producteur_has_Produit_Produit1_idx` (`produitId` ASC) VISIBLE,
  CONSTRAINT `fk_Producteur_has_Produit_Producteur1`
    FOREIGN KEY (`producteurId`)
    REFERENCES `jumbofood`.`producteur` (`id`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_Producteur_has_Produit_Produit1`
    FOREIGN KEY (`produitId`)
    REFERENCES `jumbofood`.`produit` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `jumbofood`.`ropert`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jumbofood`.`ropert` (
  `nom` VARCHAR(45) NULL DEFAULT NULL,
  `motPasse` VARCHAR(1000) NULL DEFAULT NULL,
  `prenom` VARCHAR(45) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
